# Generated by Django 2.2.2 on 2020-03-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='color_label', to='tables.Color'),
            preserve_default=False,
        ),
    ]
