# Generated by Django 2.2.2 on 2020-03-08 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_label_color_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name_checklist', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CheckList',
                'ordering': ['name_checklist'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name_item', models.CharField(max_length=255)),
                ('check_item', models.BooleanField(default=False)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReName', to='tables.Table')),
            ],
            options={
                'verbose_name_plural': 'Item',
                'ordering': ['name_item'],
            },
        ),
    ]
