# Generated by Django 3.0.8 on 2020-07-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_checklist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='background_table',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
